-- MySQL Script generated by MySQL Workbench
-- Tue May  7 13:36:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema love_note
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema love_note
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `love_note` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `love_note` ;

-- -----------------------------------------------------
-- Table `love_note`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `phone` CHAR(15) NOT NULL,
  `password` VARCHAR(32) NULL,
  `sex` TINYINT NULL,
  `birthday` BIGINT NULL,
  `user_token` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  UNIQUE INDEX `user_token_UNIQUE` (`user_token` ASC),
  INDEX `index_status` (`status` ASC),
  INDEX `index_create` (`create_at` ASC),
  INDEX `index_update` (`update_at` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`couple`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`couple` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `together_at` BIGINT NULL,
  `creator_id` BIGINT NOT NULL,
  `invitee_id` BIGINT NOT NULL,
  `creator_name` VARCHAR(20) NULL,
  `invitee_name` VARCHAR(20) NULL,
  `creator_avatar` TEXT NULL,
  `invitee_avatar` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_couple_user_idx` (`creator_id` ASC),
  INDEX `fk_couple_user_idx1` (`invitee_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_id` (`status` ASC, `id` ASC),
  INDEX `index_q_status_cid_iid` (`status` ASC, `creator_id` ASC, `invitee_id` ASC),
  INDEX `index_q_status_iid` (`status` ASC, `invitee_id` ASC),
  CONSTRAINT `fk_couple_user1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_couple_user2`
    FOREIGN KEY (`invitee_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`trends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`trends` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `action_type` INT NULL,
  `content_type` INT NULL,
  `content_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trends_user_idx` (`user_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_trends_couple_idx` (`couple_id` ASC),
  INDEX `index_q_status_update_cid_uid` (`status` ASC, `update_at` ASC, `couple_id` ASC, `user_id` ASC),
  INDEX `index_q_status_uid_cid_atp_ctp_conid` (`status` ASC, `user_id` ASC, `couple_id` ASC, `action_type` ASC, `content_type` ASC, `content_id` ASC),
  CONSTRAINT `fk_trends_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trends_couple`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`word`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`word` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `content_text` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_word_user_idx` (`user_id` ASC),
  INDEX `fk_word_couple_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_cid_create` (`status` ASC, `couple_id` ASC, `create_at` ASC),
  CONSTRAINT `fk_word_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_word_couple`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`diary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`diary` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `happen_at` BIGINT NULL,
  `content_text` TEXT NULL,
  `content_images` TEXT NULL,
  `read_count` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_charity_user1_idx` (`user_id` ASC),
  INDEX `fk_charity_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_uid_cid_happen` (`status` ASC, `user_id` ASC, `couple_id` ASC, `happen_at` ASC),
  INDEX `index_q_status_cid_happen` (`status` ASC, `couple_id` ASC, `happen_at` ASC),
  CONSTRAINT `fk_charity_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_charity_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`album` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `title` VARCHAR(45) NULL,
  `cover` TEXT NULL,
  `start_at` BIGINT NULL,
  `end_at` BIGINT NULL,
  `picture_count` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_album_user1_idx` (`user_id` ASC),
  INDEX `fk_album_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_cid_end` (`status` ASC, `couple_id` ASC, `end_at` ASC),
  CONSTRAINT `fk_album_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_album_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`picture` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `album_id` BIGINT NOT NULL,
  `happen_at` BIGINT NULL,
  `content_image` TEXT NULL,
  `longitude` DOUBLE NULL,
  `latitude` DOUBLE NULL,
  `address` VARCHAR(200) NULL,
  `city_id` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_picture_user1_idx` (`user_id` ASC),
  INDEX `fk_picture_couple1_idx` (`couple_id` ASC),
  INDEX `fk_picture_album1_idx` (`album_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_happen_aid` (`status` ASC, `happen_at` ASC, `album_id` ASC),
  INDEX `index_q_status_cid_aid_happen` (`status` ASC, `couple_id` ASC, `album_id` ASC, `happen_at` ASC),
  CONSTRAINT `fk_picture_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_picture_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_picture_album1`
    FOREIGN KEY (`album_id`)
    REFERENCES `love_note`.`album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`angry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`angry` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `happen_id` BIGINT NOT NULL,
  `happen_at` BIGINT NULL,
  `content_text` TEXT NULL,
  `gift_id` BIGINT NULL,
  `promise_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_angry_user1_idx` (`user_id` ASC),
  INDEX `fk_angry_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_angry_user2_idx` (`happen_id` ASC),
  INDEX `angry_gift1_idx` (`gift_id` ASC),
  INDEX `angry_promise1_idx` (`promise_id` ASC),
  INDEX `index_q_status_cid_happen_hid` (`status` ASC, `couple_id` ASC, `happen_at` ASC, `happen_id` ASC),
  CONSTRAINT `fk_angry_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_angry_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_angry_user2`
    FOREIGN KEY (`happen_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`award_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`award_rule` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `title` TEXT NULL,
  `score` INT NULL,
  `use_count` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_award_rule_user1_idx` (`user_id` ASC),
  INDEX `fk_award_rule_couple1_idx` (`couple_id` ASC),
  INDEX `index_q_status_cid_create` (`status` ASC, `couple_id` ASC, `create_at` ASC),
  CONSTRAINT `fk_award_rule_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_award_rule_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`award`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`award` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '		',
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `happen_id` BIGINT NOT NULL,
  `award_rule_id` BIGINT NOT NULL,
  `happen_at` BIGINT NULL,
  `content_text` TEXT NULL,
  `score_change` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_award_user1_idx` (`user_id` ASC),
  INDEX `fk_award_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_award_award_rule1_idx` (`award_rule_id` ASC),
  INDEX `fk_award_user2_idx` (`happen_id` ASC),
  INDEX `index_q_status_cid_happen_hid` (`status` ASC, `couple_id` ASC, `happen_at` ASC, `happen_id` ASC),
  CONSTRAINT `fk_award_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_award_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_award_award_rule1`
    FOREIGN KEY (`award_rule_id`)
    REFERENCES `love_note`.`award_rule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_award_user2`
    FOREIGN KEY (`happen_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`travel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`travel` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `happen_at` BIGINT NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_travel_user1_idx` (`user_id` ASC),
  INDEX `fk_travel_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_cid_happen` (`status` ASC, `couple_id` ASC, `happen_at` ASC),
  CONSTRAINT `fk_travel_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`dream`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`dream` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `happen_at` BIGINT NULL,
  `content_text` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dream_user1_idx` (`user_id` ASC),
  INDEX `fk_dream_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_cid_happen_uid` (`status` ASC, `couple_id` ASC, `happen_at` ASC, `user_id` ASC),
  CONSTRAINT `fk_dream_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dream_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`gift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`gift` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `receive_id` BIGINT NOT NULL,
  `happen_at` BIGINT NULL,
  `title` VARCHAR(45) NULL,
  `content_images` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_gift_user1_idx` (`user_id` ASC),
  INDEX `fk_gift_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_gift_user2_idx` (`receive_id` ASC),
  INDEX `index_q_status_cid_happen_rid` (`status` ASC, `couple_id` ASC, `happen_at` ASC, `receive_id` ASC),
  CONSTRAINT `fk_gift_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gift_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gift_user2`
    FOREIGN KEY (`receive_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`whisper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`whisper` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `channel` VARCHAR(45) NULL,
  `is_image` TINYINT NULL,
  `content` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_whisper_user1_idx` (`user_id` ASC),
  INDEX `fk_whisper_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_cid_channel_create` (`status` ASC, `couple_id` ASC, `channel` ASC, `create_at` ASC),
  CONSTRAINT `fk_whisper_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_whisper_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`version` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `platform` VARCHAR(45) NULL,
  `version_name` VARCHAR(15) NULL,
  `version_code` INT NULL,
  `update_log` TEXT NULL,
  `update_url` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`entry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`entry` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `device_id` VARCHAR(100) NULL,
  `device_name` VARCHAR(45) NULL,
  `market` VARCHAR(45) NULL,
  `language` VARCHAR(45) NULL,
  `platform` VARCHAR(20) NULL,
  `os_version` VARCHAR(45) NULL,
  `app_version` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_entry_user1_idx` (`user_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_uid` (`status` ASC, `user_id` ASC),
  CONSTRAINT `fk_entry_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`suggest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`suggest` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `kind` INT NULL,
  `title` VARCHAR(45) NULL,
  `content_text` TEXT NULL,
  `content_image` TEXT NULL,
  `top` TINYINT NULL,
  `official` TINYINT NULL,
  `follow_count` INT NULL,
  `comment_count` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_suggest_user1_idx` (`user_id` ASC),
  INDEX `index_q_status_uid_update` (`status` ASC, `user_id` ASC, `update_at` ASC),
  INDEX `index_q_top_update_status_kind` (`top` ASC, `update_at` ASC, `status` ASC, `kind` ASC),
  CONSTRAINT `fk_suggest_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`suggest_follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`suggest_follow` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `suggest_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_point_suggest_user1_idx` (`user_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_suggest_point_suggest1_idx` (`suggest_id` ASC),
  INDEX `index_q_uid_sid` (`user_id` ASC, `suggest_id` ASC),
  INDEX `index_q_status_uid_update` (`status` ASC, `user_id` ASC, `update_at` ASC),
  CONSTRAINT `fk_point_suggest_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suggest_point_suggest1`
    FOREIGN KEY (`suggest_id`)
    REFERENCES `love_note`.`suggest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`notice` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `title` VARCHAR(45) NULL,
  `content_type` INT NULL,
  `content_text` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`suggest_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`suggest_comment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `suggest_id` BIGINT NOT NULL,
  `official` TINYINT NULL,
  `content_text` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_comment_user1_idx` (`user_id` ASC),
  INDEX `fk_suggest_comment_suggest1_idx` (`suggest_id` ASC),
  INDEX `index_q_status_sid_uid` (`status` ASC, `suggest_id` ASC, `user_id` ASC),
  INDEX `index_q_status_sid_official_create` (`status` ASC, `suggest_id` ASC, `official` ASC, `create_at` ASC),
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suggest_comment_suggest1`
    FOREIGN KEY (`suggest_id`)
    REFERENCES `love_note`.`suggest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`promise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`promise` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `happen_id` BIGINT NOT NULL,
  `happen_at` BIGINT NULL,
  `content_text` TEXT NULL,
  `break_count` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_promise_user1_idx` (`user_id` ASC),
  INDEX `fk_promise_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_promise_user2_idx` (`happen_id` ASC),
  INDEX `index_q_status_cid_happen_hid` (`status` ASC, `couple_id` ASC, `happen_at` ASC, `happen_id` ASC),
  CONSTRAINT `fk_promise_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promise_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promise_user2`
    FOREIGN KEY (`happen_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`souvenir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`souvenir` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `happen_at` BIGINT NULL,
  `title` VARCHAR(45) NULL,
  `done` TINYINT NULL,
  `longitude` DOUBLE NULL,
  `latitude` DOUBLE NULL,
  `address` VARCHAR(200) NULL,
  `city_id` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_sounevir_user1_idx` (`user_id` ASC),
  INDEX `fk_sounevir_couple1_idx` (`couple_id` ASC),
  INDEX `index_q_status_cid_done_happen` (`status` ASC, `couple_id` ASC, `done` ASC, `happen_at` ASC),
  CONSTRAINT `fk_sounevir_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sounevir_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`coin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`coin` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `kind` INT NULL,
  `bill_id` BIGINT NULL,
  `change` INT NULL,
  `count` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_coin_user1_idx` (`user_id` ASC),
  INDEX `fk_coin_couple1_idx` (`couple_id` ASC),
  INDEX `index_q_status_cid_create` (`status` ASC, `couple_id` ASC, `create_at` ASC),
  INDEX `index_q_status_cid_bid` (`status` ASC, `couple_id` ASC, `bill_id` ASC),
  INDEX `index_q_status_create_uid_cid_kind` (`status` ASC, `create_at` ASC, `user_id` ASC, `couple_id` ASC, `kind` ASC),
  CONSTRAINT `fk_coin_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coin_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`wall_paper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`wall_paper` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `couple_id` BIGINT NOT NULL,
  `content_images` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_bg_couple_couple1_idx` (`couple_id` ASC),
  INDEX `index_q_status_cid` (`status` ASC, `couple_id` ASC),
  CONSTRAINT `fk_bg_couple_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`notice_read`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`notice_read` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `notice_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notice_read_user1_idx` (`user_id` ASC),
  INDEX `fk_notice_read_notice1_idx` (`notice_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_uid_nid` (`status` ASC, `user_id` ASC, `notice_id` ASC),
  CONSTRAINT `fk_notice_read_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notice_read_notice1`
    FOREIGN KEY (`notice_id`)
    REFERENCES `love_note`.`notice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`place` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `longitude` DOUBLE NULL,
  `latitude` DOUBLE NULL,
  `address` VARCHAR(200) NULL,
  `country` VARCHAR(100) NULL,
  `province` VARCHAR(100) NULL,
  `city` VARCHAR(100) NULL,
  `district` VARCHAR(100) NULL,
  `street` VARCHAR(100) NULL,
  `city_id` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_place_user1_idx` (`user_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_place_couple1_idx` (`couple_id` ASC),
  INDEX `index_q_status_cid_create_uid` (`status` ASC, `couple_id` ASC, `create_at` ASC, `user_id` ASC),
  CONSTRAINT `fk_place_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_place_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`vip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`vip` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `from_type` INT NULL,
  `bill_id` BIGINT NULL,
  `expire_days` INT NULL,
  `expire_at` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vip_user1_idx` (`user_id` ASC),
  INDEX `fk_vip_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_cid_expireAt` (`status` ASC, `couple_id` ASC, `expire_at` ASC),
  INDEX `index_q_status_cid_create_bid` (`status` ASC, `couple_id` ASC, `create_at` ASC, `bill_id` ASC),
  CONSTRAINT `fk_vip_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vip_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`sign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`sign` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `year` INT NULL,
  `month_of_year` INT NULL,
  `day_of_month` INT NULL,
  `continue_day` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sign_user1_idx` (`user_id` ASC),
  INDEX `fk_sign_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_cid_year_month_create_day` (`status` ASC, `couple_id` ASC, `year` ASC, `month_of_year` ASC, `create_at` ASC, `day_of_month` ASC),
  CONSTRAINT `fk_sign_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sign_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`video` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `happen_at` BIGINT NULL,
  `title` VARCHAR(45) NULL,
  `content_thumb` TEXT NULL,
  `content_video` TEXT NULL,
  `duration` INT NULL,
  `longitude` DOUBLE NULL,
  `latitude` DOUBLE NULL,
  `address` VARCHAR(200) NULL,
  `city_id` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_video_user1_idx` (`user_id` ASC),
  INDEX `fk_video_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_cid_happen` (`status` ASC, `couple_id` ASC, `happen_at` ASC),
  CONSTRAINT `fk_video_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`audio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`audio` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `happen_at` BIGINT NULL,
  `title` VARCHAR(45) NULL,
  `content_audio` TEXT NULL,
  `duration` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_audio_user1_idx` (`user_id` ASC),
  INDEX `fk_audio_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_cid_happen` (`status` ASC, `couple_id` ASC, `happen_at` ASC),
  CONSTRAINT `fk_audio_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audio_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`sms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`sms` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `phone` CHAR(15) NULL,
  `send_type` INT NULL,
  `content` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_create_phone_type` (`status` ASC, `create_at` ASC, `phone` ASC, `send_type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`couple_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`couple_state` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `state` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_couple_state_couple1_idx` (`couple_id` ASC),
  INDEX `fk_couple_state_user1_idx` (`user_id` ASC),
  INDEX `index_q_status_cid_state_create` (`status` ASC, `couple_id` ASC, `state` ASC, `create_at` ASC),
  CONSTRAINT `fk_couple_state_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_couple_state_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`menses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`menses` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `year` INT NULL,
  `month_of_year` INT NULL,
  `day_of_month` INT NULL,
  `is_start` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menses_user1_idx` (`user_id` ASC),
  INDEX `fk_menses_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_uid_cid_create_year_month` (`status` ASC, `user_id` ASC, `couple_id` ASC, `create_at` ASC, `year` ASC, `month_of_year` ASC),
  INDEX `index_q_status_cid_year_month_day` (`status` ASC, `couple_id` ASC, `year` ASC, `month_of_year` ASC, `day_of_month` ASC),
  CONSTRAINT `fk_menses_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menses_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`sleep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`sleep` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `year` INT NULL,
  `month_of_year` INT NULL,
  `day_of_month` INT NULL,
  `is_sleep` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sleep_user1_idx` (`user_id` ASC),
  INDEX `fk_sleep_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_uid_cid_create` (`status` ASC, `user_id` ASC, `couple_id` ASC, `create_at` ASC),
  INDEX `index_q_status_cid_year_month_create` (`status` ASC, `couple_id` ASC, `year` ASC, `month_of_year` ASC, `create_at` ASC),
  INDEX `index_q_status_uid_cid_year_month_day` (`status` ASC, `user_id` ASC, `couple_id` ASC, `year` ASC, `month_of_year` ASC, `day_of_month` ASC),
  CONSTRAINT `fk_sleep_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sleep_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`promise_break`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`promise_break` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `promise_id` BIGINT NOT NULL,
  `happen_at` BIGINT NULL,
  `content_text` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_promise_break_user1_idx` (`user_id` ASC),
  INDEX `fk_promise_break_couple1_idx` (`couple_id` ASC),
  INDEX `fk_promise_break_promise1_idx` (`promise_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_cid_pid_happen` (`status` ASC, `couple_id` ASC, `promise_id` ASC, `happen_at` ASC),
  CONSTRAINT `fk_promise_break_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promise_break_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promise_break_promise1`
    FOREIGN KEY (`promise_id`)
    REFERENCES `love_note`.`promise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`food` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `happen_at` BIGINT NULL,
  `title` VARCHAR(45) NULL,
  `content_images` TEXT NULL,
  `content_text` TEXT NULL,
  `longitude` DOUBLE NULL,
  `latitude` DOUBLE NULL,
  `address` VARCHAR(200) NULL,
  `city_id` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_food_user1_idx` (`user_id` ASC),
  INDEX `fk_food_couple1_idx` (`couple_id` ASC),
  INDEX `index_q_status_cid_happen` (`status` ASC, `couple_id` ASC, `happen_at` ASC),
  CONSTRAINT `fk_food_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_food_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`travel_place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`travel_place` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `travel_id` BIGINT NOT NULL,
  `happen_at` BIGINT NULL,
  `content_text` TEXT NULL,
  `longitude` DOUBLE NULL,
  `latitude` DOUBLE NULL,
  `address` VARCHAR(200) NULL,
  `city_id` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_travel_place_user1_idx` (`user_id` ASC),
  INDEX `fk_travel_place_couple1_idx` (`couple_id` ASC),
  INDEX `fk_travel_place_travel1_idx` (`travel_id` ASC),
  INDEX `index_q_status_cid_tid_happen` (`status` ASC, `couple_id` ASC, `travel_id` ASC, `happen_at` ASC),
  CONSTRAINT `fk_travel_place_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_place_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_place_travel1`
    FOREIGN KEY (`travel_id`)
    REFERENCES `love_note`.`travel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`travel_album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`travel_album` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `travel_id` BIGINT NOT NULL,
  `album_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_travel_album_travel1_idx` (`travel_id` ASC),
  INDEX `fk_travel_album_album1_idx` (`album_id` ASC),
  INDEX `fk_travel_album_user1_idx` (`user_id` ASC),
  INDEX `fk_travel_album_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_cid_tid_update_aid` (`status` ASC, `couple_id` ASC, `travel_id` ASC, `update_at` ASC, `album_id` ASC),
  CONSTRAINT `fk_travel_album_travel1`
    FOREIGN KEY (`travel_id`)
    REFERENCES `love_note`.`travel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_album_album1`
    FOREIGN KEY (`album_id`)
    REFERENCES `love_note`.`album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_album_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_album_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`travel_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`travel_video` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `travel_id` BIGINT NOT NULL,
  `video_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_travel_video_user1_idx` (`user_id` ASC),
  INDEX `fk_travel_video_couple1_idx` (`couple_id` ASC),
  INDEX `fk_travel_video_travel1_idx` (`travel_id` ASC),
  INDEX `fk_travel_video_video1_idx` (`video_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_cid_tid_update_vid` (`status` ASC, `couple_id` ASC, `travel_id` ASC, `update_at` ASC, `video_id` ASC),
  CONSTRAINT `fk_travel_video_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_video_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_video_travel1`
    FOREIGN KEY (`travel_id`)
    REFERENCES `love_note`.`travel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_video_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `love_note`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`travel_food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`travel_food` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `travel_id` BIGINT NOT NULL,
  `food_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_travel_food_user1_idx` (`user_id` ASC),
  INDEX `fk_travel_food_couple1_idx` (`couple_id` ASC),
  INDEX `fk_travel_food_travel1_idx` (`travel_id` ASC),
  INDEX `fk_travel_food_food1_idx` (`food_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_cid_tid_update_fid` (`status` ASC, `couple_id` ASC, `travel_id` ASC, `update_at` ASC, `food_id` ASC),
  CONSTRAINT `fk_travel_food_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_food_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_food_travel1`
    FOREIGN KEY (`travel_id`)
    REFERENCES `love_note`.`travel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_food_food1`
    FOREIGN KEY (`food_id`)
    REFERENCES `love_note`.`food` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`travel_diary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`travel_diary` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `travel_id` BIGINT NOT NULL,
  `diary_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_travel_diary_user1_idx` (`user_id` ASC),
  INDEX `fk_travel_diary_couple1_idx` (`couple_id` ASC),
  INDEX `fk_travel_diary_travel1_idx` (`travel_id` ASC),
  INDEX `fk_travel_diary_diary1_idx` (`diary_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_cid_tid_update_did` (`status` ASC, `couple_id` ASC, `travel_id` ASC, `update_at` ASC, `diary_id` ASC),
  CONSTRAINT `fk_travel_diary_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_diary_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_diary_travel1`
    FOREIGN KEY (`travel_id`)
    REFERENCES `love_note`.`travel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_diary_diary1`
    FOREIGN KEY (`diary_id`)
    REFERENCES `love_note`.`diary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`shy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`shy` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `year` INT NULL,
  `month_of_year` INT NULL,
  `day_of_month` INT NULL,
  `happen_at` BIGINT NULL,
  `end_at` BIGINT NULL,
  `safe` VARCHAR(45) NULL,
  `desc` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shy_user1_idx` (`user_id` ASC),
  INDEX `fk_shy_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_cid_year_month_happen` (`status` ASC, `couple_id` ASC, `year` ASC, `month_of_year` ASC, `happen_at` ASC),
  INDEX `index_q_status_uid_cid_year_month_day` (`status` ASC, `user_id` ASC, `couple_id` ASC, `year` ASC, `month_of_year` ASC, `day_of_month` ASC),
  CONSTRAINT `fk_shy_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shy_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`lock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`lock` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `password` VARCHAR(32) NULL,
  `is_lock` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lock_user1_idx` (`user_id` ASC),
  INDEX `fk_lock_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_uid_cid` (`status` ASC, `user_id` ASC, `couple_id` ASC),
  CONSTRAINT `fk_lock_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lock_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`souvenir_gift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`souvenir_gift` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `souvenir_id` BIGINT NOT NULL,
  `gift_id` BIGINT NOT NULL,
  `year` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_souvenir_gift_user1_idx` (`user_id` ASC),
  INDEX `fk_souvenir_gift_couple1_idx` (`couple_id` ASC),
  INDEX `fk_souvenir_gift_souvenir1_idx` (`souvenir_id` ASC),
  INDEX `fk_souvenir_gift_gift1_idx` (`gift_id` ASC),
  INDEX `index_q_status_cid_sid_update_gid` (`status` ASC, `couple_id` ASC, `souvenir_id` ASC, `update_at` ASC, `gift_id` ASC),
  CONSTRAINT `fk_souvenir_gift_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_gift_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_gift_souvenir1`
    FOREIGN KEY (`souvenir_id`)
    REFERENCES `love_note`.`souvenir` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_gift_gift1`
    FOREIGN KEY (`gift_id`)
    REFERENCES `love_note`.`gift` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`souvenir_travel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`souvenir_travel` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `souvenir_id` BIGINT NOT NULL,
  `travel_id` BIGINT NOT NULL,
  `year` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_souvenir_trvel_user1_idx` (`user_id` ASC),
  INDEX `fk_souvenir_trvel_couple1_idx` (`couple_id` ASC),
  INDEX `fk_souvenir_trvel_souvenir1_idx` (`souvenir_id` ASC),
  INDEX `fk_souvenir_trvel_travel1_idx` (`travel_id` ASC),
  INDEX `index_q_status_cid_sid_update_tid` (`status` ASC, `couple_id` ASC, `souvenir_id` ASC, `update_at` ASC, `travel_id` ASC),
  CONSTRAINT `fk_souvenir_trvel_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_trvel_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_trvel_souvenir1`
    FOREIGN KEY (`souvenir_id`)
    REFERENCES `love_note`.`souvenir` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_trvel_travel1`
    FOREIGN KEY (`travel_id`)
    REFERENCES `love_note`.`travel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`souvenir_album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`souvenir_album` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `souvenir_id` BIGINT NOT NULL,
  `album_id` BIGINT NOT NULL,
  `year` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_souvenir_album_user1_idx` (`user_id` ASC),
  INDEX `fk_souvenir_album_couple1_idx` (`couple_id` ASC),
  INDEX `fk_souvenir_album_souvenir1_idx` (`souvenir_id` ASC),
  INDEX `fk_souvenir_album_album1_idx` (`album_id` ASC),
  INDEX `index_q_status_cid_sid_update_aid` (`status` ASC, `couple_id` ASC, `souvenir_id` ASC, `update_at` ASC, `album_id` ASC),
  CONSTRAINT `fk_souvenir_album_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_album_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_album_souvenir1`
    FOREIGN KEY (`souvenir_id`)
    REFERENCES `love_note`.`souvenir` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_album_album1`
    FOREIGN KEY (`album_id`)
    REFERENCES `love_note`.`album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`souvenir_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`souvenir_video` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `souvenir_id` BIGINT NOT NULL,
  `video_id` BIGINT NOT NULL,
  `year` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_souvenir_video_user1_idx` (`user_id` ASC),
  INDEX `fk_souvenir_video_couple1_idx` (`couple_id` ASC),
  INDEX `fk_souvenir_video_souvenir1_idx` (`souvenir_id` ASC),
  INDEX `fk_souvenir_video_video1_idx` (`video_id` ASC),
  INDEX `index_q_status_cid_sid_update_vid` (`status` ASC, `couple_id` ASC, `souvenir_id` ASC, `update_at` ASC, `video_id` ASC),
  CONSTRAINT `fk_souvenir_video_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_video_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_video_souvenir1`
    FOREIGN KEY (`souvenir_id`)
    REFERENCES `love_note`.`souvenir` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_video_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `love_note`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`souvenir_food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`souvenir_food` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `souvenir_id` BIGINT NOT NULL,
  `food_id` BIGINT NOT NULL,
  `year` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_souvenir_food_user1_idx` (`user_id` ASC),
  INDEX `fk_souvenir_food_couple1_idx` (`couple_id` ASC),
  INDEX `fk_souvenir_food_souvenir1_idx` (`souvenir_id` ASC),
  INDEX `fk_souvenir_food_food1_idx` (`food_id` ASC),
  INDEX `index_q_status_cid_sid_update_fid` (`status` ASC, `couple_id` ASC, `souvenir_id` ASC, `update_at` ASC, `food_id` ASC),
  CONSTRAINT `fk_souvenir_food_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_food_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_food_souvenir1`
    FOREIGN KEY (`souvenir_id`)
    REFERENCES `love_note`.`souvenir` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_food_food1`
    FOREIGN KEY (`food_id`)
    REFERENCES `love_note`.`food` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`souvenir_diary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`souvenir_diary` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `souvenir_id` BIGINT NOT NULL,
  `diary_id` BIGINT NOT NULL,
  `year` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_souvenir_diary_user1_idx` (`user_id` ASC),
  INDEX `fk_souvenir_diary_couple1_idx` (`couple_id` ASC),
  INDEX `fk_souvenir_diary_souvenir1_idx` (`souvenir_id` ASC),
  INDEX `fk_souvenir_diary_diary1_idx` (`diary_id` ASC),
  INDEX `index_q_status_cid_sid_update_did` (`status` ASC, `couple_id` ASC, `souvenir_id` ASC, `update_at` ASC, `diary_id` ASC),
  CONSTRAINT `fk_souvenir_diary_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_diary_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_diary_souvenir1`
    FOREIGN KEY (`souvenir_id`)
    REFERENCES `love_note`.`souvenir` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_diary_diary1`
    FOREIGN KEY (`diary_id`)
    REFERENCES `love_note`.`diary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`topic_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`topic_message` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `to_user_id` BIGINT NOT NULL,
  `to_couple_id` BIGINT NOT NULL,
  `kind` INT NULL,
  `content_text` TEXT NULL,
  `content_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_topic_message_user1_idx` (`user_id` ASC),
  INDEX `fk_topic_message_couple1_idx` (`couple_id` ASC),
  INDEX `fk_topic_message_user2_idx` (`to_user_id` ASC),
  INDEX `fk_topic_message_couple2_idx` (`to_couple_id` ASC),
  INDEX `index_q_status_tuid_tcid_create_kind` (`status` ASC, `to_user_id` ASC, `to_couple_id` ASC, `create_at` ASC, `kind` ASC),
  INDEX `index_q_status_update_tuid_tcid` (`status` ASC, `update_at` ASC, `to_user_id` ASC, `to_couple_id` ASC),
  CONSTRAINT `fk_topic_message_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topic_message_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topic_message_user2`
    FOREIGN KEY (`to_user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topic_message_couple2`
    FOREIGN KEY (`to_couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`post` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `kind` INT NULL,
  `sub_kind` INT NULL,
  `title` VARCHAR(45) NULL,
  `content_text` TEXT NULL,
  `content_images` TEXT NULL,
  `top` TINYINT NULL,
  `official` TINYINT NULL,
  `well` TINYINT NULL,
  `report_count` INT NULL,
  `point_count` INT NULL,
  `collect_count` INT NULL,
  `comment_count` INT NULL,
  INDEX `fk_post_user1_idx` (`user_id` ASC),
  INDEX `fk_post_couple1_idx` (`couple_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_uid_cid_kind_update` (`status` ASC, `user_id` ASC, `couple_id` ASC, `kind` ASC, `update_at` ASC),
  INDEX `index_q_status_create_report_kind_top_update_sub` (`status` ASC, `create_at` ASC, `report_count` ASC, `kind` ASC, `top` ASC, `update_at` ASC, `sub_kind` ASC),
  INDEX `index_q_status_title_report_update` (`status` ASC, `title` ASC, `report_count` ASC, `update_at` ASC),
  INDEX `index_q_status_create_report_top_update` (`status` ASC, `create_at` ASC, `report_count` ASC, `top` ASC, `update_at` ASC),
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`post_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`post_comment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `post_id` BIGINT NOT NULL,
  `to_comment_id` BIGINT NULL,
  `floor` INT NULL,
  `kind` INT NULL,
  `content_text` TEXT NULL,
  `official` TINYINT NULL,
  `sub_comment_count` INT NULL,
  `report_count` INT NULL,
  `point_count` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_comment_user1_idx` (`user_id` ASC),
  INDEX `fk_post_comment_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_to_comment_id` (`to_comment_id` ASC),
  INDEX `fk_post_comment_post1_idx` (`post_id` ASC),
  INDEX `index_q_status_pid_tcid_create` (`status` ASC, `post_id` ASC, `to_comment_id` ASC, `create_at` ASC),
  INDEX `index_q_status_uid_cid_pid_tcid_kind` (`status` ASC, `user_id` ASC, `couple_id` ASC, `post_id` ASC, `to_comment_id` ASC, `kind` ASC),
  INDEX `index_q_status_pid_tcid_report_official_point_uid` (`status` ASC, `post_id` ASC, `to_comment_id` ASC, `report_count` ASC, `official` ASC, `point_count` ASC, `user_id` ASC),
  INDEX `index_q_status_pid_tcid_report_official_create_uid` (`status` ASC, `post_id` ASC, `to_comment_id` ASC, `report_count` ASC, `official` ASC, `create_at` ASC, `user_id` ASC),
  CONSTRAINT `fk_post_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_comment_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_comment_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `love_note`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`post_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`post_report` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `post_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_report_user1_idx` (`user_id` ASC),
  INDEX `fk_post_report_couple1_idx` (`couple_id` ASC),
  INDEX `fk_post_report_post1_idx` (`post_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_uid_cid_pid` (`status` ASC, `user_id` ASC, `couple_id` ASC, `post_id` ASC),
  CONSTRAINT `fk_post_report_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_report_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_report_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `love_note`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`post_point`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`post_point` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `post_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_point_user1_idx` (`user_id` ASC),
  INDEX `fk_post_point_couple1_idx` (`couple_id` ASC),
  INDEX `fk_post_point_post1_idx` (`post_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_uid_cid_pid` (`user_id` ASC, `couple_id` ASC, `post_id` ASC),
  CONSTRAINT `fk_post_point_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_point_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_point_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `love_note`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`post_collect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`post_collect` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `post_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_collect_user1_idx` (`user_id` ASC),
  INDEX `fk_post_collect_couple1_idx` (`couple_id` ASC),
  INDEX `fk_post_collect_post1_idx` (`post_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_uid_cid_pid` (`user_id` ASC, `couple_id` ASC, `post_id` ASC),
  INDEX `index_q_status_uid_cid_update` (`status` ASC, `user_id` ASC, `couple_id` ASC, `update_at` ASC),
  CONSTRAINT `fk_post_collect_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_collect_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_collect_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `love_note`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`post_comment_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`post_comment_report` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `post_comment_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_comment_report_user1_idx` (`user_id` ASC),
  INDEX `fk_post_comment_report_couple1_idx` (`couple_id` ASC),
  INDEX `fk_post_comment_report_post_comment1_idx` (`post_comment_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_uid_cid_pcid` (`status` ASC, `user_id` ASC, `couple_id` ASC, `post_comment_id` ASC),
  CONSTRAINT `fk_post_comment_report_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_comment_report_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_comment_report_post_comment1`
    FOREIGN KEY (`post_comment_id`)
    REFERENCES `love_note`.`post_comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`post_comment_point`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`post_comment_point` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `post_comment_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_post_comment_point_user1_idx` (`user_id` ASC),
  INDEX `fk_post_comment_point_couple1_idx` (`couple_id` ASC),
  INDEX `fk_post_comment_point_post_comment1_idx` (`post_comment_id` ASC),
  INDEX `index_q_uid_cid_picd` (`user_id` ASC, `couple_id` ASC, `post_comment_id` ASC),
  CONSTRAINT `fk_post_comment_point_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_comment_point_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_comment_point_post_comment1`
    FOREIGN KEY (`post_comment_id`)
    REFERENCES `love_note`.`post_comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`post_read`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`post_read` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `post_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_read_user1_idx` (`user_id` ASC),
  INDEX `fk_post_read_post1_idx` (`post_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_uid_pid` (`status` ASC, `user_id` ASC, `post_id` ASC),
  CONSTRAINT `fk_post_read_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_read_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `love_note`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`topic_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`topic_info` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `kind` INT NULL,
  `year` INT NULL,
  `day_of_year` INT NULL,
  `post_count` INT NULL,
  `browse_count` INT NULL,
  `comment_count` INT NULL,
  `report_count` INT NULL,
  `point_count` INT NULL,
  `collect_count` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_kind_year_day` (`status` ASC, `kind` ASC, `year` ASC, `day_of_year` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`broadcast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`broadcast` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `title` VARCHAR(100) NULL,
  `cover` TEXT NULL,
  `start_at` BIGINT NULL,
  `end_at` BIGINT NULL,
  `content_type` INT NULL,
  `content_text` TEXT NULL,
  `is_end` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_start_end_end` (`status` ASC, `start_at` ASC, `end_at` ASC, `is_end` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`award_score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`award_score` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `change_count` INT NULL,
  `total_score` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_award_score_user1_idx` (`user_id` ASC),
  INDEX `fk_award_score_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_uid_cid` (`status` ASC, `user_id` ASC, `couple_id` ASC),
  CONSTRAINT `fk_award_score_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_award_score_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`bill` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `platform_os` VARCHAR(45) NULL,
  `platform_pay` INT NULL,
  `pay_type` INT NULL,
  `pay_amount` DOUBLE NULL,
  `trade_no` VARCHAR(100) NULL,
  `trade_receipt` TEXT NULL,
  `trade_pay` TINYINT NULL,
  `goods_type` INT NULL,
  `goods_out` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bill_user1_idx` (`user_id` ASC),
  INDEX `fk_bill_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_uid_cid_tradePay_goodsOut_create` (`status` ASC, `user_id` ASC, `couple_id` ASC, `trade_pay` ASC, `goods_out` ASC, `create_at` ASC),
  INDEX `index_q_tradeNo_tradeReceipt` (`trade_no` ASC, `trade_receipt` ASC),
  CONSTRAINT `fk_bill_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bill_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`match_period`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`match_period` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `start_at` BIGINT NULL,
  `end_at` BIGINT NULL,
  `period` INT NULL,
  `kind` INT NULL,
  `title` VARCHAR(100) NULL,
  `coin_change` INT NULL,
  `works_count` INT NULL,
  `report_count` INT NULL,
  `point_count` INT NULL,
  `coin_count` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_kind_start_end` (`status` ASC, `kind` ASC, `start_at` ASC, `end_at` ASC),
  INDEX `index_q_status_kind_period` (`status` ASC, `kind` ASC, `period` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`match_work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`match_work` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `match_period_id` BIGINT NOT NULL,
  `kind` INT NULL,
  `title` VARCHAR(200) NULL,
  `content_text` TEXT NULL,
  `content_image` TEXT NULL,
  `report_count` INT NULL,
  `point_count` INT NULL,
  `coin_count` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_match_work_user1_idx` (`user_id` ASC),
  INDEX `fk_match_work_couple1_idx` (`couple_id` ASC),
  INDEX `fk_match_work_match_period1_idx` (`match_period_id` ASC),
  INDEX `index_q_status_cid_kind_create` (`status` ASC, `couple_id` ASC, `kind` ASC, `create_at` ASC),
  INDEX `index_q_uid_cid_mpid` (`user_id` ASC, `couple_id` ASC, `match_period_id` ASC),
  INDEX `index_q_status_mpid_report` (`status` ASC, `match_period_id` ASC, `report_count` ASC),
  CONSTRAINT `fk_match_work_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_work_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_work_match_period1`
    FOREIGN KEY (`match_period_id`)
    REFERENCES `love_note`.`match_period` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`match_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`match_report` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `match_period_id` BIGINT NOT NULL,
  `match_work_id` BIGINT NOT NULL,
  `reason` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_match_report_match_period1_idx` (`match_period_id` ASC),
  INDEX `fk_match_report_match_work1_idx` (`match_work_id` ASC),
  INDEX `fk_match_report_user1_idx` (`user_id` ASC),
  INDEX `fk_match_report_couple1_idx` (`couple_id` ASC),
  INDEX `index_q_status_uid_cid_work` (`status` ASC, `user_id` ASC, `couple_id` ASC, `match_work_id` ASC),
  CONSTRAINT `fk_match_report_match_period1`
    FOREIGN KEY (`match_period_id`)
    REFERENCES `love_note`.`match_period` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_report_match_work1`
    FOREIGN KEY (`match_work_id`)
    REFERENCES `love_note`.`match_work` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_report_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_report_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`match_point`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`match_point` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `match_period_id` BIGINT NOT NULL,
  `match_work_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_match_point_match_period1_idx` (`match_period_id` ASC),
  INDEX `fk_match_point_match_work1_idx` (`match_work_id` ASC),
  INDEX `fk_match_point_user1_idx` (`user_id` ASC),
  INDEX `fk_match_point_couple1_idx` (`couple_id` ASC),
  INDEX `index_q_uid_cid_work` (`user_id` ASC, `couple_id` ASC, `match_work_id` ASC),
  CONSTRAINT `fk_match_point_match_period1`
    FOREIGN KEY (`match_period_id`)
    REFERENCES `love_note`.`match_period` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_point_match_work1`
    FOREIGN KEY (`match_work_id`)
    REFERENCES `love_note`.`match_work` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_point_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_point_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`match_coin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`match_coin` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `match_period_id` BIGINT NOT NULL,
  `match_work_id` BIGINT NOT NULL,
  `coin_id` BIGINT NOT NULL,
  `coin_count` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_match_coin_match_period1_idx` (`match_period_id` ASC),
  INDEX `fk_match_coin_match_work1_idx` (`match_work_id` ASC),
  INDEX `fk_match_coin_coin1_idx` (`coin_id` ASC),
  INDEX `fk_match_coin_user1_idx` (`user_id` ASC),
  INDEX `fk_match_coin_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_uid_cid_work` (`status` ASC, `user_id` ASC, `couple_id` ASC, `match_work_id` ASC),
  CONSTRAINT `fk_match_coin_match_period1`
    FOREIGN KEY (`match_period_id`)
    REFERENCES `love_note`.`match_period` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_coin_match_work1`
    FOREIGN KEY (`match_work_id`)
    REFERENCES `love_note`.`match_work` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_coin_coin1`
    FOREIGN KEY (`coin_id`)
    REFERENCES `love_note`.`coin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_coin_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_coin_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`administer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`administer` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `permission` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_administer_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_administer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`api`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`api` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NULL,
  `platform` VARCHAR(45) NULL,
  `language` VARCHAR(45) NULL,
  `uri` VARCHAR(100) NULL,
  `method` VARCHAR(45) NULL,
  `params` TEXT NULL,
  `body` TEXT NULL,
  `result` TEXT NULL,
  `duration` DOUBLE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`movie` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `happen_at` BIGINT NULL,
  `title` VARCHAR(45) NULL,
  `content_images` TEXT NULL,
  `content_text` TEXT NULL,
  `longitude` DOUBLE NULL,
  `latitude` DOUBLE NULL,
  `address` VARCHAR(200) NULL,
  `city_id` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movie_user1_idx` (`user_id` ASC),
  INDEX `fk_movie_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_cid_happen` (`status` ASC, `couple_id` ASC, `happen_at` ASC),
  CONSTRAINT `fk_movie_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`souvenir_movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`souvenir_movie` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `souvenir_id` BIGINT NOT NULL,
  `movie_id` BIGINT NOT NULL,
  `year` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_souvenir_movie_user1_idx` (`user_id` ASC),
  INDEX `fk_souvenir_movie_couple1_idx` (`couple_id` ASC),
  INDEX `fk_souvenir_movie_souvenir1_idx` (`souvenir_id` ASC),
  INDEX `fk_souvenir_movie_movie1_idx` (`movie_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_cid_sid_update_mid` (`status` ASC, `couple_id` ASC, `souvenir_id` ASC, `update_at` ASC, `movie_id` ASC),
  CONSTRAINT `fk_souvenir_movie_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_movie_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_movie_souvenir1`
    FOREIGN KEY (`souvenir_id`)
    REFERENCES `love_note`.`souvenir` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souvenir_movie_movie1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `love_note`.`movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`travel_movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`travel_movie` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `travel_id` BIGINT NOT NULL,
  `movie_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_travel_movie_user1_idx` (`user_id` ASC),
  INDEX `fk_travel_movie_couple1_idx` (`couple_id` ASC),
  INDEX `fk_travel_movie_travel1_idx` (`travel_id` ASC),
  INDEX `fk_travel_movie_movie1_idx` (`movie_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_cid_tid_update_mid` (`status` ASC, `couple_id` ASC, `travel_id` ASC, `update_at` ASC, `movie_id` ASC),
  CONSTRAINT `fk_travel_movie_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_movie_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_movie_travel1`
    FOREIGN KEY (`travel_id`)
    REFERENCES `love_note`.`travel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_movie_movie1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `love_note`.`movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`menses_length`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`menses_length` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `cycle_day` INT NULL,
  `duration_day` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menses_length_user1_idx` (`user_id` ASC),
  INDEX `fk_menses_length_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_uid_cid` (`status` ASC, `user_id` ASC, `couple_id` ASC),
  CONSTRAINT `fk_menses_length_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menses_length_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`menses2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`menses2` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `start_at` BIGINT NULL,
  `end_at` BIGINT NULL,
  `start_year` INT NULL,
  `start_month_of_year` INT NULL,
  `start_day_of_month` INT NULL,
  `end_year` INT NULL,
  `end_month_of_year` INT NULL,
  `end_day_of_month` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_menses2_user1_idx` (`user_id` ASC),
  INDEX `fk_menses2_couple1_idx` (`couple_id` ASC),
  INDEX `index_q_status_uid_cid_sy_sm_sd` (`status` ASC, `user_id` ASC, `couple_id` ASC, `start_year` ASC, `start_month_of_year` ASC, `start_day_of_month` ASC),
  INDEX `index_q_status_uid_cid_ey_em_ed` (`status` ASC, `user_id` ASC, `couple_id` ASC, `end_year` ASC, `end_month_of_year` ASC, `end_day_of_month` ASC),
  INDEX `index_q_status_uid_cid_start_end` (`status` ASC, `user_id` ASC, `couple_id` ASC, `start_at` ASC, `end_at` ASC),
  INDEX `index_q_uid_cid_sy_sm_sd` (`user_id` ASC, `couple_id` ASC, `start_year` ASC, `start_month_of_year` ASC, `start_day_of_month` ASC),
  CONSTRAINT `fk_menses2_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menses2_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`menses_day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`menses_day` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  `menses2_id` BIGINT NOT NULL,
  `year` INT NULL,
  `month_of_year` INT NULL,
  `day_of_month` INT NULL,
  `blood` INT NULL,
  `pain` INT NULL,
  `mood` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menses_day_user1_idx` (`user_id` ASC),
  INDEX `fk_menses_day_couple1_idx` (`couple_id` ASC),
  INDEX `fk_menses_day_menses21_idx` (`menses2_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_mid_year_month_day` (`status` ASC, `menses2_id` ASC, `year` ASC, `month_of_year` ASC, `day_of_month` ASC),
  CONSTRAINT `fk_menses_day_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menses_day_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menses_day_menses21`
    FOREIGN KEY (`menses2_id`)
    REFERENCES `love_note`.`menses2` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`trends_browse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`trends_browse` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trends_browse_user1_idx` (`user_id` ASC),
  INDEX `fk_trends_browse_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_uid_cid` (`status` ASC, `user_id` ASC, `couple_id` ASC),
  CONSTRAINT `fk_trends_browse_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trends_browse_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `love_note`.`topic_message_browse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `love_note`.`topic_message_browse` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `create_at` BIGINT NULL,
  `update_at` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `couple_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_topic_message_browse_user1_idx` (`user_id` ASC),
  INDEX `fk_topic_message_browse_couple1_idx` (`couple_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index_q_status_uid_cid` (`status` ASC, `user_id` ASC, `couple_id` ASC),
  CONSTRAINT `fk_topic_message_browse_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `love_note`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topic_message_browse_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `love_note`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
